; Rotom syntax highlighting
; Matches the node types generated by tree-sitter-rotom grammar

; Keywords — anonymous terminals (appear inside seq rules)
[
  "if" "then" "else" "endif"
  "while" "do" "endwhile"
  "match" "with" "case" "endmatch"
  "Jump" "EndMovement"
  "script" "action"
  "alias" "as"
] @keyword

; Keywords — named leaf nodes (rule body is just the literal)
[
  (break_statement)
  (return_statement)
  (end_statement)
] @keyword

; Boolean literals
(boolean) @boolean

; Literals
(number) @number
(string) @string
(escape_sequence) @escape
(comment) @comment

; Operators — "not" is also a prefix keyword but classified as operator here
[
  "==" "!=" "<=" ">=" "<" ">" "&&" "||"
  "+" "-" "*"
  "!" "not"
  "(" ")" "," "#" ":"
] @operator

; Preprocessor
(preprocessor_directive) @preproc

; Expression identifiers — variable first, ALL_CAPS constants override (last wins)
(expression (identifier) @variable)

(expression
  (identifier) @constant
  (#match? @constant "^[A-Z][A-Z0-9_]*$"))

; Alias target: `alias expr as Name`
(alias_statement
  "as"
  (identifier) @variable)

; Definition names — @type is teal in Zed/VS Code (do not use @label here)
(function_header name: (identifier) @type)

(action_definition name: (identifier) @type)

(label_definition name: (identifier) @type)

(local_label_definition (local_label) @type)

; Jump targets — same @type as label/script references
(jump_statement "Jump" (identifier) @type)

(jump_statement "Jump" (local_label) @type)

; Command invocations — Zed resolves @function.call then falls back to @function
(command_statement name: (identifier) @function @function.call)

(movement_statement command: (identifier) @function @function.call)
