; Rotom syntax highlighting
; Matches the node types generated by tree-sitter-rotom grammar

; Keywords — anonymous terminals (appear inside seq rules)
[
  "if" "then" "else" "endif"
  "while" "do" "endwhile"
  "match" "with" "case" "endmatch"
  "Jump" "EndMovement"
  "script" "action"
  "alias" "as"
] @keyword

; Keywords — named leaf nodes (rule body is just the literal)
[
  (break_statement)
  (return_statement)
  (end_statement)
] @keyword

; Boolean literals
(boolean) @boolean

; Definitions
(function_header (identifier) @function)
(action_definition (identifier) @function)
(label_definition (identifier) @function)
(local_label_definition (local_label) @function)

; Command invocations
(command_statement (identifier) @function.call)

; Literals
(number) @number
(string) @string
(escape_sequence) @escape
(comment) @comment

; Variables / identifiers
(identifier) @variable
(local_label) @variable

; Operators — "not" is also a prefix keyword but classified as operator here
[
  "==" "!=" "<=" ">=" "<" ">" "&&" "||"
  "+" "-" "*"
  "!" "not"
  "(" ")" "," "#" ":"
] @operator

; Preprocessor
(preprocessor_directive) @preproc
